[build-system]
requires = [
    "setuptools>=75.1.0",
    "wheel>=0.44.0",
    "Cython>=3.0.11",
    "numpy>=2.1.2",
    "networkx>=3.4.1",
    "matplotlib>=3.9.2"
]

build-backend = "setuptools.build_meta"